name: nerf_pl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_2
  - cudatoolkit=11.1.1=h6406543_8
  - cudnn=8.2.1.32=h86fa8c9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=7.31.1=py37h06a4308_0
  - jedi=0.18.1=py37h06a4308_1
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py37h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.8.0=py3.7_cuda11.1_cudnn8.0.5_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.0=py37
  - torchvision=0.9.0=py37_cu111
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - antlr4-python3-runtime==4.8
    - anyio==3.5.0
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - autopep8==1.6.0
    - babel==2.9.1
    - beautifulsoup4==4.10.0
    - black==21.4b2
    - bleach==4.1.0
    - cached-property==1.5.2
    - cachetools==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.0.0
    - cmapy==0.6.6
    - colorlog==6.6.0
    - commonmark==0.9.1
    - configargparse==1.5.3
    - cycler==0.11.0
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - detectron2==0.6
    - dotmap==1.3.26
    - editdistance==0.6.0
    - einops==0.4.0
    - entrypoints==0.4
    - filelock==3.6.0
    - fire==0.4.0
    - fonttools==4.29.1
    - fsspec==2022.2.0
    - future==0.18.2
    - fvcore==0.1.5.post20220414
    - gdown==4.4.0
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - h5py==3.6.0
    - huggingface-hub==0.4.0
    - hydra-colorlog==1.1.0
    - hydra-core==1.1.2
    - idna==3.3
    - imageio==2.16.0
    - imath==0.0.1
    - importlib-metadata==4.11.1
    - importlib-resources==5.2.3
    - iopath==0.1.9
    - ipdb==0.13.9
    - ipykernel==6.9.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jarowinkler==1.0.2
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-packaging==0.11.1
    - jupyter-server==1.13.5
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - kornia==0.6.3
    - lpips==0.1.4
    - markdown==3.3.6
    - markupsafe==2.1.0
    - mathutils==2.81.2
    - matplotlib==3.5.1
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclassic==0.3.5
    - nbclient==0.5.11
    - nbconvert==6.4.2
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - notebook==6.4.8
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - open3d==0.14.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - pathspec==0.9.0
    - pillow==9.0.1
    - piq==0.6.0
    - plyfile==0.7.4
    - polygon3==3.0.9.1
    - portalocker==2.4.0
    - prometheus-client==0.13.1
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pycodestyle==2.8.0
    - pycparser==2.21
    - pydot==1.4.2
    - pyhocon==0.3.59
    - pymcubes==0.1.2
    - pyparsing==2.4.7
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytorch-lightning==0.10.0
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - rapidfuzz==2.0.11
    - regex==2022.1.18
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rich==12.3.0
    - rsa==4.8
    - sacremoses==0.0.47
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scikit-video==1.1.11
    - scipy==1.7.3
    - send2trash==1.8.0
    - shapely==1.8.1.post1
    - sniffio==1.2.0
    - soupsieve==2.3.1
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - terminado==0.13.1
    - test-tube==0.7.5
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.5.4
    - tokenizers==0.11.5
    - toml==0.10.2
    - tomlkit==0.10.0
    - tornado==6.1
    - tqdm==4.62.3
    - transformers==4.16.2
    - typed-ast==1.5.3
    - typing-extensions==4.2.0
    - urllib3==1.26.8
    - vit-pytorch==0.26.7
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - werkzeug==2.0.3
    - wheel==0.37.1
    - widgetsnbextension==3.5.2
    - yacs==0.1.8
    - zipp==3.7.0
